name: indexed_entity_store
description: A fast, simple, and synchronous entity store for Flutter applications.
version: 1.4.7
repository: https://github.com/LunaONE/indexed_entity_store

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqlite3: ^2.4.6

  disposable_value_listenable: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  path_provider: ^2.1.4
